
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Audit Tasks      <small><?= cclang('detail', ['Audit Tasks']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/audit_tasks'); ?>">Audit Tasks</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Audit Tasks</h3>
                     <h5 class="widget-user-desc">Detail Audit Tasks</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal form-step" name="form_audit_tasks" id="form_audit_tasks" >
                  
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                        <span class="detail_group-id"><?= _ent($audit_tasks->id); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Perusahaan </label>

                        <div class="col-sm-8">
                        <span class="detail_group-nama_perusahaan"><?= _ent($audit_tasks->nama_perusahaan); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kantor Cabang </label>

                        <div class="col-sm-8">
                        <span class="detail_group-kantor_cabang"><?= _ent($audit_tasks->kantor_cabang); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Industri </label>

                        <div class="col-sm-8">
                        <span class="detail_group-jenis_industri"><?= _ent($audit_tasks->jenis_industri); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lingkup Audit </label>

                        <div class="col-sm-8">
                          <?= join_multi_select($audit_tasks->lingkup_audit, 'kriteria_audit', 'no_kriteria', 'kriteria'); ?>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal </label>

                        <div class="col-sm-8">
                        <span class="detail_group-tanggal"><?= _ent($audit_tasks->tanggal); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tempat </label>

                        <div class="col-sm-8">
                        <span class="detail_group-tempat"><?= _ent($audit_tasks->tempat); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tujuan </label>

                        <div class="col-sm-8">
                        <span class="detail_group-tujuan"><?= _ent($audit_tasks->tujuan); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Proses Produksi </label>

                        <div class="col-sm-8">
                        <span class="detail_group-proses_produksi"><?= _ent($audit_tasks->proses_produksi); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Penerapan K3 </label>

                        <div class="col-sm-8">
                        <span class="detail_group-penerapan_k3"><?= _ent($audit_tasks->penerapan_k3); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jadwal </label>

                        <div class="col-sm-8">
                        <span class="detail_group-jadwal"><?= _ent($audit_tasks->jadwal); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kriteria Audit </label>

                        <div class="col-sm-8">
                        <span class="detail_group-kriteria_audit"><?= _ent($audit_tasks->kriteria_audit); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ket Kriteria Tdk Berlaku </label>

                        <div class="col-sm-8">
                        <span class="detail_group-ket_kriteria_tdk_berlaku"><?= _ent($audit_tasks->ket_kriteria_tdk_berlaku); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Uraian Tdk Sesuai </label>

                        <div class="col-sm-8">
                        <span class="detail_group-uraian_tdk_sesuai"><?= _ent($audit_tasks->uraian_tdk_sesuai); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Uraian Temuan </label>

                        <div class="col-sm-8">
                        <span class="detail_group-uraian_temuan"><?= _ent($audit_tasks->uraian_temuan); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lead </label>

                        <div class="col-sm-8">
                        <span class="detail_group-lead"><?= _ent($audit_tasks->lead); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Member1 </label>

                        <div class="col-sm-8">
                        <span class="detail_group-member1"><?= _ent($audit_tasks->member1); ?></span>
                        </div>
                    </div>
                                        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Member2 </label>

                        <div class="col-sm-8">
                        <span class="detail_group-member2"><?= _ent($audit_tasks->member2); ?></span>
                        </div>
                    </div>
                                        
                    <br>
                    <br>


                     
                         
                    <div class="view-nav">
                        <?php is_allowed('audit_tasks_update', function() use ($audit_tasks){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit audit_tasks (Ctrl+e)" href="<?= site_url('administrator/audit_tasks/edit/'.$audit_tasks->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Audit Tasks']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/audit_tasks/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Audit Tasks']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<script>
$(document).ready(function(){
   (function(){
        var nama_perusahaan = $('.detail_group-nama_perusahaan');
        var kantor_cabang = $('.detail_group-kantor_cabang');
        var jenis_industri = $('.detail_group-jenis_industri');
        var lingkup_audit = $('.detail_group-lingkup_audit');
        var tanggal = $('.detail_group-tanggal');
        var tempat = $('.detail_group-tempat');
        var tujuan = $('.detail_group-tujuan');
        var proses_produksi = $('.detail_group-proses_produksi');
        var penerapan_k3 = $('.detail_group-penerapan_k3');
        var jadwal = $('.detail_group-jadwal');
        var kriteria_audit = $('.detail_group-kriteria_audit');
        var ket_kriteria_tdk_berlaku = $('.detail_group-ket_kriteria_tdk_berlaku');
        var uraian_tdk_sesuai = $('.detail_group-uraian_tdk_sesuai');
        var uraian_temuan = $('.detail_group-uraian_temuan');
        var lead = $('.detail_group-lead');
        var member1 = $('.detail_group-member1');
        var member2 = $('.detail_group-member2');
    })()
      
   });
</script>