
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Audit_tasks/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('audit_tasks') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('audit_tasks') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('audit_tasks_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('audit_tasks')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/audit_tasks/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('audit_tasks')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('audit_tasks_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('audit_tasks') ?> " href="<?= site_url('administrator/audit_tasks/export?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                                             </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('audit_tasks') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('audit_tasks')]); ?>  <i class="label bg-yellow"><?= $audit_tasks_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_audit_tasks" id="form_audit_tasks" action="<?= base_url('administrator/audit_tasks/index'); ?>">
                  


                     <!-- /.widget-user -->
                  <div class="row">
                     <div class="col-md-8">
                                                <div class="col-sm-2 padd-left-0 " >
                           <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                                                         <option value="delete">Delete</option>
                                                      </select>
                        </div>
                        <div class="col-sm-2 padd-left-0 ">
                           <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                        </div>
                                                <div class="col-sm-3 padd-left-0  " >
                           <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                        </div>
                        <div class="col-sm-3 padd-left-0 " >
                           <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                              <option value=""><?= cclang('all'); ?></option>
                               <option <?= $this->input->get('f') == 'nama_perusahaan' ? 'selected' :''; ?> value="nama_perusahaan">Nama Perusahaan</option>
                            <option <?= $this->input->get('f') == 'kantor_cabang' ? 'selected' :''; ?> value="kantor_cabang">Kantor Cabang</option>
                            <option <?= $this->input->get('f') == 'jenis_industri' ? 'selected' :''; ?> value="jenis_industri">Jenis Industri</option>
                            <option <?= $this->input->get('f') == 'lingkup_audit' ? 'selected' :''; ?> value="lingkup_audit">Lingkup Audit</option>
                            <option <?= $this->input->get('f') == 'tanggal' ? 'selected' :''; ?> value="tanggal">Tanggal</option>
                            <option <?= $this->input->get('f') == 'tempat' ? 'selected' :''; ?> value="tempat">Tempat</option>
                            <option <?= $this->input->get('f') == 'tujuan' ? 'selected' :''; ?> value="tujuan">Tujuan</option>
                            <option <?= $this->input->get('f') == 'proses_produksi' ? 'selected' :''; ?> value="proses_produksi">Proses Produksi</option>
                            <option <?= $this->input->get('f') == 'penerapan_k3' ? 'selected' :''; ?> value="penerapan_k3">Penerapan K3</option>
                            <option <?= $this->input->get('f') == 'jadwal' ? 'selected' :''; ?> value="jadwal">Jadwal</option>
                            <option <?= $this->input->get('f') == 'kriteria_audit' ? 'selected' :''; ?> value="kriteria_audit">Kriteria Audit</option>
                            <option <?= $this->input->get('f') == 'ket_kriteria_tdk_berlaku' ? 'selected' :''; ?> value="ket_kriteria_tdk_berlaku">Ket Kriteria Tdk Berlaku</option>
                            <option <?= $this->input->get('f') == 'uraian_tdk_sesuai' ? 'selected' :''; ?> value="uraian_tdk_sesuai">Uraian Tdk Sesuai</option>
                            <option <?= $this->input->get('f') == 'uraian_temuan' ? 'selected' :''; ?> value="uraian_temuan">Uraian Temuan</option>
                            <option <?= $this->input->get('f') == 'lead' ? 'selected' :''; ?> value="lead">Lead</option>
                            <option <?= $this->input->get('f') == 'member1' ? 'selected' :''; ?> value="member1">Member1</option>
                            <option <?= $this->input->get('f') == 'member2' ? 'selected' :''; ?> value="member2">Member2</option>
                           </select>
                        </div>
                        <div class="col-sm-1 padd-left-0 ">
                           <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                           Filter
                           </button>
                        </div>
                        <div class="col-sm-1 padd-left-0 ">
                           <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/audit_tasks');?>" title="<?= cclang('reset_filter'); ?>">
                           <i class="fa fa-undo"></i>
                           </a>
                        </div>
                     </div>
                     <div class="col-md-4">
                        <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                           <?= $pagination; ?>
                        </div>
                     </div>
                  </div>
                  <div class="table-responsive"> 

                  <br>
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th data-field="nama_perusahaan"data-sort="1" data-primary-key="0"> <?= cclang('nama_perusahaan') ?></th>
                           <th data-field="kantor_cabang"data-sort="1" data-primary-key="0"> <?= cclang('kantor_cabang') ?></th>
                           <th data-field="jenis_industri"data-sort="1" data-primary-key="0"> <?= cclang('jenis_industri') ?></th>
                           <th data-field="lingkup_audit"data-sort="1" data-primary-key="0"> <?= cclang('lingkup_audit') ?></th>
                           <th data-field="tanggal"data-sort="1" data-primary-key="0"> <?= cclang('tanggal') ?></th>
                           <th data-field="tempat"data-sort="1" data-primary-key="0"> <?= cclang('tempat') ?></th>
                           <th data-field="tujuan"data-sort="1" data-primary-key="0"> <?= cclang('tujuan') ?></th>
                           <th data-field="proses_produksi"data-sort="1" data-primary-key="0"> <?= cclang('proses_produksi') ?></th>
                           <th data-field="penerapan_k3"data-sort="1" data-primary-key="0"> <?= cclang('penerapan_k3') ?></th>
                           <th data-field="jadwal"data-sort="1" data-primary-key="0"> <?= cclang('jadwal') ?></th>
                           <th data-field="kriteria_audit"data-sort="1" data-primary-key="0"> <?= cclang('kriteria_audit') ?></th>
                           <th data-field="ket_kriteria_tdk_berlaku"data-sort="1" data-primary-key="0"> <?= cclang('ket_kriteria_tdk_berlaku') ?></th>
                           <th data-field="uraian_tdk_sesuai"data-sort="1" data-primary-key="0"> <?= cclang('uraian_tdk_sesuai') ?></th>
                           <th data-field="uraian_temuan"data-sort="1" data-primary-key="0"> <?= cclang('uraian_temuan') ?></th>
                           <th data-field="lead"data-sort="1" data-primary-key="0"> <?= cclang('lead') ?></th>
                           <th data-field="member1"data-sort="1" data-primary-key="0"> <?= cclang('member1') ?></th>
                           <th data-field="member2"data-sort="1" data-primary-key="0"> <?= cclang('member2') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_audit_tasks">
                     <?php foreach($audit_taskss as $audit_tasks): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $audit_tasks->id; ?>">
                           </td>
                                                       
                           <td><span class="list_group-nama_perusahaan"><?= _ent($audit_tasks->nama_perusahaan); ?></span></td> 
                           <td><span class="list_group-kantor_cabang"><?= _ent($audit_tasks->kantor_cabang); ?></span></td> 
                           <td><span class="list_group-jenis_industri"><?= _ent($audit_tasks->jenis_industri); ?></span></td> 
                           <td><?= join_multi_select($audit_tasks->lingkup_audit, 'kriteria_audit', 'no_kriteria', 'kriteria'); ?></td> 
                           <td><span class="list_group-tanggal"><?= _ent($audit_tasks->tanggal); ?></span></td> 
                           <td><span class="list_group-tempat"><?= _ent($audit_tasks->tempat); ?></span></td> 
                           <td><span class="list_group-tujuan"><?= _ent($audit_tasks->tujuan); ?></span></td> 
                           <td><span class="list_group-proses_produksi"><?= _ent($audit_tasks->proses_produksi); ?></span></td> 
                           <td><span class="list_group-penerapan_k3"><?= _ent($audit_tasks->penerapan_k3); ?></span></td> 
                           <td><span class="list_group-jadwal"><?= _ent($audit_tasks->jadwal); ?></span></td> 
                           <td><span class="list_group-kriteria_audit"><?= _ent($audit_tasks->kriteria_audit); ?></span></td> 
                           <td><span class="list_group-ket_kriteria_tdk_berlaku"><?= _ent($audit_tasks->ket_kriteria_tdk_berlaku); ?></span></td> 
                           <td><span class="list_group-uraian_tdk_sesuai"><?= _ent($audit_tasks->uraian_tdk_sesuai); ?></span></td> 
                           <td><span class="list_group-uraian_temuan"><?= _ent($audit_tasks->uraian_temuan); ?></span></td> 
                           <td><span class="list_group-lead"><?= _ent($audit_tasks->lead); ?></span></td> 
                           <td><span class="list_group-member1"><?= _ent($audit_tasks->member1); ?></span></td> 
                           <td><span class="list_group-member2"><?= _ent($audit_tasks->member2); ?></span></td> 
                           <td width="200">
                            
                                                              <?php is_allowed('audit_tasks_view', function() use ($audit_tasks){?>
                                                              <a href="<?= site_url('administrator/audit_tasks/view/' . $audit_tasks->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('audit_tasks_update', function() use ($audit_tasks){?>
                              <a href="<?= site_url('administrator/audit_tasks/edit/' . $audit_tasks->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('audit_tasks_delete', function() use ($audit_tasks){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/audit_tasks/delete/' . $audit_tasks->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($audit_tasks_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Audit Tasks data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
             
            </div>
            </form>            
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->

<script>
  $(document).ready(function(){
   
    (function(){

})()
      
      
      $('.table tbody tr').each(function(){
         var row = $(this);
         (function(){
    var nama_perusahaan = row.find('.list_group-nama_perusahaan');
    var kantor_cabang = row.find('.list_group-kantor_cabang');
    var jenis_industri = row.find('.list_group-jenis_industri');
    var lingkup_audit = row.find('.list_group-lingkup_audit');
    var tanggal = row.find('.list_group-tanggal');
    var tempat = row.find('.list_group-tempat');
    var tujuan = row.find('.list_group-tujuan');
    var proses_produksi = row.find('.list_group-proses_produksi');
    var penerapan_k3 = row.find('.list_group-penerapan_k3');
    var jadwal = row.find('.list_group-jadwal');
    var kriteria_audit = row.find('.list_group-kriteria_audit');
    var ket_kriteria_tdk_berlaku = row.find('.list_group-ket_kriteria_tdk_berlaku');
    var uraian_tdk_sesuai = row.find('.list_group-uraian_tdk_sesuai');
    var uraian_temuan = row.find('.list_group-uraian_temuan');
    var lead = row.find('.list_group-lead');
    var member1 = row.find('.list_group-member1');
    var member2 = row.find('.list_group-member2');

})()
      })
      
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_audit_tasks').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/audit_tasks/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('audit_tasks', $('table.dataTable'));
  }); /*end doc ready*/
</script>