<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
    //This page is a result of an autogenerated content made by running test.html with firefox.
    function domo() {

        // Binding keys
        $('*').bind('keydown', 'Ctrl+e', function assets() {
            $('#btn_edit').trigger('click');
            return false;
        });

        $('*').bind('keydown', 'Ctrl+x', function assets() {
            $('#btn_back').trigger('click');
            return false;
        });

    }


    jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Audit Tasks <small><?= cclang('detail', ['Audit Tasks']); ?> </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class=""><a href="<?= site_url('administrator/audit_tasks'); ?>">Audit Tasks</a></li>
        <li class="active"><?= cclang('detail'); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-body ">

                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header ">

                            <div class="widget-user-image">
                                <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                            </div>
                            <!-- /.widget-user-image -->
                            <h3 class="widget-user-username">Audit Tasks</h3>
                            <h5 class="widget-user-desc">Detail Audit Tasks</h5>
                            <hr>
                        </div>


                        <div class="form-horizontal form-step" name="form_audit_tasks" id="form_audit_tasks">
                            <div class="container">
                                <div class="form-group ">
                                    <table class="table table-hover table-bordered">
                                        <thead class="bg-info">
                                            <tr>
                                                <th scope="col" rowspan="3">No</th>
                                                <th scope="col" rowspan="3">No Kriteria</th>
                                                <th scope="col" rowspan="3">ID</th>
                                                <th scope="col" rowspan="3">Interpretasi Kriteria</th>
                                                <th scope="col" rowspan="3">Tidak Berlaku</th>
                                                <th scope="col" colspan="4">Pemenuhannya</th>

                                            </tr>
                                            <tr>
                                                <th rowspan="2">sesuai</th>
                                                <th colspan="2">Ketidaksesuaian</th>
                                                <th rowspan="2">observasi</th>
                                            </tr>
                                            <tr>
                                                <th>major</th>
                                                <th>minor</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?= form_open('', [
                                                'name' => 'audit_pemenuhan',
                                                'id' => 'audit_pemenuhan',
                                                'enctype' => 'multipart/form-data',
                                                'method' => 'POST'
                                            ]); ?>
                                            <?php $no = 1;
                                            foreach (db_get_all_data('master_interpretasi_kriteria_audit') as $audit) : ?>
                                                <tr>
                                                    <td class="text-center"><?= $no; ?></td>
                                                    <td class="text-right"><?= $audit->id_kriteria; ?></td>
                                                    <td class="text-center"><?= $audit->id; ?></td>
                                                    <td><?= $audit->interpretasi_kriteria; ?></td>
                                                    <td class="text-center">
                                                        <input type="radio" name="radio_<?= _ent($audit->id) ?>" data-id="<?= $audit->id; ?>" data-no="<?= $audit->id; ?>" data-value="<?= $audit->interpretasi_kriteria ?>" value="tidak_berlaku">
                                                    </td>
                                                    <td class="text-center">
                                                        <input type="radio" name="radio_<?= _ent($audit->id) ?>" data-id="<?= $audit->id; ?>" value="sesuai">
                                                    </td>
                                                    <td class="text-center">
                                                        <input type="radio" name="radio_<?= _ent($audit->id) ?>" data-id="<?= $audit->id; ?>" data-no="<?= $audit->id; ?>" data-value="<?= $audit->interpretasi_kriteria ?>" value="major">
                                                    </td>
                                                    <td class="text-center">
                                                        <input type="radio" name="radio_<?= _ent($audit->id) ?>" data-id="<?= $audit->id; ?>" data-no="<?= $audit->id; ?>" data-value="<?= $audit->interpretasi_kriteria ?>" value="minor">
                                                    </td>
                                                    <td class="text-center">
                                                        <input type="radio" name="radio_<?= _ent($audit->id) ?>" data-id="<?= $audit->id; ?>" data-no="<?= $audit->id; ?>" data-value="<?= $audit->interpretasi_kriteria ?>" value="observasi">
                                                    </td>
                                                </tr>
                                            <?php $no++;
                                            endforeach; ?>
                                        </tbody>
                                        <?= form_close(); ?>

                                    </table>
                                </div>
                                <form action="" id="tidak_berlaku">
                                    <u>
                                        <h4>PENJELASAN TENTANG KRITERIA TIDAK BERLAKU</h4>
                                    </u>
                                    <div class="tidak_berlaku">

                                    </div>
                                </form>
                                <hr>
                                <form action="" id="tidak_sesuai">
                                    <u>
                                        <h4>TEMUAN KETIDAK SESUAIAN</h4>
                                    </u>
                                    <div class="tidak_sesuai">

                                    </div>
                                </form>
                                <hr>
                                <form action="" id="observasi">
                                    <u>
                                        <h4>TEMUAN OBSERVASI</h4>
                                    </u>
                                    <div class="observasi">

                                    </div>
                                </form>
                                <hr>

                            </div>


                            <div class="message"></div>
                            <br>
                            <br>

                            <div class="view-nav">
                                <div class="row-fluid col-md-7 container-button-bottom">
                                    <button class="btn btn-flat btn-primary btn_save btn_action" id="btn_save" data-stype='stay' title="<?= cclang('save_button'); ?> (Ctrl+s)">
                                        <i class="fa fa-save"></i> <?= cclang('save_button'); ?>
                                    </button>
                                    <a class="btn btn-flat btn-info btn_save btn_action btn_save_back" id="btn_save" data-stype='back' title="<?= cclang('save_and_go_the_list_button'); ?> (Ctrl+d)">
                                        <i class="ion ion-ios-list-outline"></i> <?= cclang('save_and_go_the_list_button'); ?>
                                    </a>

                                    <div class="custom-button-wrapper">

                                    </div>


                                    <a class="btn btn-flat btn-default btn_action" id="btn_cancel" title="<?= cclang('cancel_button'); ?> (Ctrl+x)">
                                        <i class="fa fa-undo"></i> <?= cclang('cancel_button'); ?>
                                    </a>

                                    <span class="loading loading-hide">
                                        <img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg">
                                        <i><?= cclang('loading_saving_data'); ?></i>
                                    </span>
                                </div>
                            </div>

                            <hr>



                        </div>
                    </div>
                </div>
                <!--/box body -->
            </div>
            <!--/box -->


            <!-- modal penjelasan -->

            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel"></h4>
                        </div>
                        <div class="modal-body">
                            <div class="explained-modal">

                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-info" data-dismiss="modal"><i class="fa fa-save"></i> Simpan</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- /.content -->

<script>
    function bindingValue(namee, value) {
        $('textarea[name="' + namee + '"]').val(value);
    }
    $(document).ready(function() {
        $('input[type="radio"]').iCheck({
            radioClass: 'iradio_minimal-blue'
        });

        $('input').on('ifChecked', function() {
            const modal = $('.explained-modal');
            const data_value = $(this).attr('data-value');
            const data_no = $(this).attr('data-no');
            const data_id = $(this).attr('data-id');
            modal.empty();

            if ($(this).val() == 'tidak_berlaku') {
                $(".tidak_sesuai_" + data_id).remove();
                $(".observasi_" + data_id).remove();


                const target = $('.tidak_berlaku');
                const targetClass = 'penjelasan_' + data_id;

                $('#myModal').modal('show');
                let htmlModal = '';
                let html = '<div class="input-group ' + targetClass + '" style="margin-bottom:10px">';
                html += '<p>Kriteria ' + data_no + ' : ';
                html += '<b> "' + data_value + '"</b></p>';
                htmlModal = html;
                htmlModal += '<textarea id="' + targetClass + '" onchange="bindingValue(this.id, this.value)" rows="4" class="textarea form-control" placeholder="Penjelasan"></textarea></div>';
                html += '<textarea name="' + targetClass + '" rows="4" class="textarea form-control" placeholder="Penjelasan"></textarea></div>';

                target.append(html);
                modal.append(htmlModal);
            } else if ($(this).val() == 'minor' || $(this).val() == 'major') {
                $(".penjelasan_" + data_id).remove();
                $(".observasi_" + data_id).remove();

                if ($(".tidak_sesuai_" + data_id)) {
                    $(".tidak_sesuai_" + data_id).remove();
                }


                const target = $('.tidak_sesuai');
                const targetClass = 'tidak_sesuai_' + data_id;

                $('#myModal').modal('show');
                let htmlModal = '';
                let html = '<div class="input-group ' + targetClass + '" style="margin-bottom:10px">';
                html += '<p>Kriteria ' + data_no + ' : ';
                html += '<b> "' + data_value + '"</b></p>';
                htmlModal = html;
                htmlModal += '<textarea id="' + targetClass + '" onchange="bindingValue(this.id, this.value)" rows="4" class="textarea form-control" placeholder="Bukti Objektif"></textarea></div>';
                html += '<textarea name="' + targetClass + '" rows="4" class="textarea form-control" placeholder="Bukti Objektif"></textarea></div>';

                target.append(html);
                modal.append(htmlModal);
            } else if ($(this).val() == 'observasi') {
                $(".penjelasan_" + data_id).remove();
                $(".tidak_sesuai_" + data_id).remove();

                const target = $('.observasi');
                const targetClass = 'observasi_' + data_id;

                $('#myModal').modal('show');
                let htmlModal = '';
                let html = '<div class="input-group ' + targetClass + '" style="margin-bottom:10px">';
                html += '<p>Kriteria ' + data_no + ' : ';
                html += '<b> "' + data_value + '"</b></p>';
                htmlModal = html;
                htmlModal += '<textarea id="' + targetClass + '" onchange="bindingValue(this.id, this.value)" rows="4" class="textarea form-control" placeholder="Observasi"></textarea></div>';
                html += '<textarea name="' + targetClass + '" rows="4" class="textarea form-control" placeholder="Observasi"></textarea></div>';

                target.append(html);
                modal.append(htmlModal);

            } else {
                $(".penjelasan_" + data_id).remove();
                $(".tidak_sesuai_" + data_id).remove();
                $(".observasi_" + data_id).remove();
            }
        });

        $('.btn_save').click(function(e) {
            e.preventDefault();
            $('.message').fadeOut();
            var audit_pemenuhan = $('#audit_pemenuhan');
            var data_post = audit_pemenuhan.serializeArray();
            var save_type = $(this).attr('data-stype');

            let tidak_berlaku = $('#tidak_berlaku').serializeArray();
            let tidak_sesuai = $('#tidak_sesuai').serializeArray();
            let observasi = $('#observasi').serializeArray();

            $.each(tidak_berlaku, function() {
                data_post.push({
                    name: this.name,
                    value: this.value
                });
            });
            $.each(tidak_sesuai, function() {
                data_post.push({
                    name: this.name,
                    value: this.value
                });
            });
            $.each(observasi, function() {
                data_post.push({
                    name: this.name,
                    value: this.value
                });
            });

            $('input[type="radio"]:checked').each(function() {
                data_post.push({
                    name: this.name,
                    value: this.value
                });
            })
            data_post.push({
                name: 'id_task',
                value: <?= $id_task; ?>
            });
            data_post.push({
                name: 'save_type',
                value: save_type
            });

            console.log(data_post)

            $('.loading').show();

            $.ajax({
                    url: BASE_URL + '/administrator/audit_tasks/save_audit_pemenuhan',
                    type: 'POST',
                    dataType: 'json',
                    data: data_post,
                })
                .done(function(res) {

                    if (res.success) {

                        if (save_type == 'back') {
                            window.location.href = res.redirect;
                            return;
                        }

                        $('.message').printMessage({
                            message: res.message
                        });
                        $('.message').fadeIn();
                        resetForm();
                        $('.chosen option').prop('selected', false).trigger('chosen:updated');
                        // ket_kriteria_tdk_berlaku.setData('');


                    } else {
                        if (res.errors) {

                            $.each(res.errors, function(index, val) {
                                $('form #' + index).parents('.form-group').addClass('has-error');
                                $('form #' + index).parents('.form-group').find('small').prepend(`
            <div class="error-input">` + val + `</div>
            `);
                            });
                            $('.steps li').removeClass('error');
                            $('.content section').each(function(index, el) {
                                if ($(this).find('.has-error').length) {
                                    $('.steps li:eq(' + index + ')').addClass('error').find('a').trigger('click');
                                }
                            });
                        }
                        $('.message').printMessage({
                            message: res.message,
                            type: 'warning'
                        });
                    }

                })
                .fail(function() {
                    $('.message').printMessage({
                        message: 'Error save data',
                        type: 'warning'
                    });
                })
                .always(function() {
                    $('.loading').hide();
                    $('html, body').animate({
                        scrollTop: $(document).height()
                    }, 2000);
                });

            return false;
        }); /*end btn save*/

    });
</script>


<script>
    function openModal() {
        $('#myModal').modal('show');
    }
</script>